[0m14:34:36.353608 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028E40251420>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028E4314FC10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028E4314F9D0>]}


============================== 14:34:36.357613 | 89ca9521-9789-4cbd-a0aa-a707db1bc295 ==============================
[0m14:34:36.357613 [info ] [MainThread]: Running with dbt=1.6.6
[0m14:34:36.358614 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\12237\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:34:42.417191 [debug] [MainThread]: Starter project path: D:\python\lib\site-packages\dbt\include\starter_project
[0m14:34:42.445613 [info ] [MainThread]: 
Your new dbt project "ass3" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:34:42.449505 [info ] [MainThread]: Setting up your profile.
[0m14:34:44.789789 [info ] [MainThread]: Profile ass3 written to C:\Users\12237\.dbt\profiles.yml using target's sample configuration. Once updated, you'll be able to start developing with dbt.
[0m14:34:44.790789 [debug] [MainThread]: Command `dbt init` succeeded at 14:34:44.790789 after 8.45 seconds
[0m14:34:44.791790 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028E40251420>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028E3BF82800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028E4314FD30>]}
[0m14:34:44.792791 [debug] [MainThread]: Flushing usage events
[0m14:42:29.030317 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028D61021480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028D63F6FE80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028D63FA41F0>]}


============================== 14:42:29.034285 | a340aad0-d172-4600-89f3-6e7c178095bb ==============================
[0m14:42:29.034285 [info ] [MainThread]: Running with dbt=1.6.6
[0m14:42:29.035194 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\12237\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt snapshot', 'send_anonymous_usage_stats': 'True'}
[0m14:42:29.035194 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\bde\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:42:29.036608 [debug] [MainThread]: Command `dbt snapshot` failed at 14:42:29.036608 after 0.03 seconds
[0m14:42:29.036608 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028D61021480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028D5CD72800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028D5CD70910>]}
[0m14:42:29.037722 [debug] [MainThread]: Flushing usage events
[0m15:14:14.467912 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022591821420>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225947C3E20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225947C3E80>]}


============================== 15:14:14.470935 | ee9eaea0-2035-434b-b161-def5a2d353d9 ==============================
[0m15:14:14.470935 [info ] [MainThread]: Running with dbt=1.6.6
[0m15:14:14.471912 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\12237\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt snapshot', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:14:14.471912 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\bde\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:14:14.473912 [debug] [MainThread]: Command `dbt snapshot` failed at 15:14:14.473912 after 0.02 seconds
[0m15:14:14.473912 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022591821420>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225947C3EE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225947C3DC0>]}
[0m15:14:14.474913 [debug] [MainThread]: Flushing usage events
[0m07:57:19.682454 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8C46A1420>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8C7543E20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8C7543E80>]}


============================== 07:57:19.686152 | f61571ea-e8c1-46c6-b11a-fa04ba05fefa ==============================
[0m07:57:19.686152 [info ] [MainThread]: Running with dbt=1.6.6
[0m07:57:19.687179 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\12237\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt snapshot', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m07:57:19.688157 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\bde\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m07:57:19.690151 [debug] [MainThread]: Command `dbt snapshot` failed at 07:57:19.690151 after 0.04 seconds
[0m07:57:19.690151 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8C46A1420>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8C7543EE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8C7543DC0>]}
[0m07:57:19.691151 [debug] [MainThread]: Flushing usage events
[0m16:40:18.599931 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000199B8631420>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000199BB543EE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000199BB543DF0>]}


============================== 16:40:18.604992 | d3309612-5552-4fdb-9605-561808c29bc1 ==============================
[0m16:40:18.604992 [info ] [MainThread]: Running with dbt=1.6.6
[0m16:40:18.606000 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\12237\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m16:40:18.607015 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\bde\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:40:18.608016 [debug] [MainThread]: Command `dbt run` failed at 16:40:18.608016 after 0.03 seconds
[0m16:40:18.608016 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000199B8631420>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000199BB543DC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000199BB543DF0>]}
[0m16:40:18.609048 [debug] [MainThread]: Flushing usage events
